### ISSUE TITLE
Convert JSON property without schema

### ISSUE THREAD

**Issue by kalu111** [Romakita/ts-express-decorators#201]
I need to decode JSON in my model property.
But the schema of that object is unknown.

```javascript
class Model {
    @JsonProperty()
    public json: Query;
}

@Converter()
class Query {
    public deserialize(data: string) {
        Object.assign(this, JSON.parse(data));
    }
}
```

Is there other (simple) solution for that?

**Comment by Romakita** [comment]
This example is wrong

**Comment by Romakita** [comment]
Can you check the documentation : https://romakita.github.io/ts-express-decorators/#/docs/converters

**Comment by kalu111** [comment]
But it works :)

**Comment by Romakita** [comment]
I think you would like something like that:

```typescript
import {IConverter, Converter} from "ts-express-decorators";

@Converter(Query)
export class QueryConverter implements IConverter {

    // Called when a date string will be deserialized from POJ
    deserialize(data: string): Query {
        return Object.assign({}, JSON.parse(data));
    }
}
```

**Comment by Romakita** [comment]
Converter decorator need a Class Type to work fine...

**Comment by kalu111** [comment]
I have only created  two classes  (see example in my first post).
And it returns an object.

**Comment by Romakita** [comment]
Well, I'm sure is not correct :). I didn't say it was not working ;)

Your example work because the converters check if a class have a method named deserialize. 
The `@Converter` decorator is not needed in this case.

In this example the @Converter isn't used => https://romakita.github.io/ts-express-decorators/#/docs/converters?id=implement-serializationdeserialization-methods

> But the schema of that object is unknown.
What is the generated schema ?

**Comment by kalu111** [comment]
> In this example the @converter isn't used => https://romakita.github.io/ts-express-decorators/#/docs/converters?id=implement-serializationdeserialization-methods

Yes, it's true :)
