### ISSUE TITLE
ServerLoader cannot be invoked without 'new'

### ISSUE THREAD

**Issue by yangukmo** [Romakita/ts-express-decorators#229]
I have a question about the error..

[Quick start with decorators](https://romakita.github.io/ts-express-decorators/#/getting-started?id=with-decorators)

I'm using version 3.9.2 and use the code in the above example and started it.
But there is an error.
How do I fix it?

```
return _super !== null && _super.apply(this, arguments) || this;
                                         ^
TypeError: Class constructor ServerLoader cannot be invoked without 'new'
```

I use it very well.
Thanks :)

----------------

It works in 2.20.0 but not 3.0.0.

**Comment by jindev** [comment]
@yangukmo it happens same issue when ts target is es5. 
it works when change ts target es6 to es2015.

**Comment by Romakita** [comment]
Hi @yangukmo,
 
Since v3, node 4 et 5 support has been removed. With node 6 and more support ES6 feature. This is why have changed the target option in the ts.config.json from es5 to es2015. (Release note: https://github.com/Romakita/ts-express-decorators/releases/tag/v3.0.0).

In fact, Ts.ED is compiled in es2015 and your project must be compiled with the same target or higher. ES5 fail and produce your error. I'm not sure why, but I thinks it's a problem between the class compiled in ES5 and ES6+  by typescript.

See you,
Romain

**Comment by yangukmo** [comment]
@Romakita @jindev 
I understand!
Grateful for help and I'm glad to be resolved.
I hope this project gets better 👍
