### ISSUE TITLE
[Question] Having issues with rootDir

### ISSUE THREAD

**Issue by TomerAmirV** [Romakita/ts-express-decorators#361]
## Informations

Type | Version
---|---
Question | 4.17.5

****

## Description
I am not sure that this is an issue with this framework or in my code, but I'm having trouble with importing files from the project root path.

let's say that my project structure is this:
```
├── controllers
│   └── ctrl.ts
├── models
│   └── model.ts
├── services
│   └── service.ts
├── package.json
├── server.ts
└── tsconifg.json
```

My `tsconfig.json`:
```json
{
	"compilerOptions": {
		"baseUrl": "./",
		"rootDir": ".",
		"outDir": "out",
		"module": "commonjs",
		"moduleResolution": "node",
		"target": "es2015",
		"noImplicitAny": false,
		"sourceMap": true,
		"declaration":false,
		"experimentalDecorators":true,
		"emitDecoratorMetadata": true,
		"isolatedModules": false,
		"suppressImplicitAnyIndexErrors": false,
		"lib": ["es6", "dom", "esnext.asynciterable"],
		"types":[
			"node",
			"jest",
			"express",
			"reflect-metadata",
			"supertest"
		]
	},

	"exclude": [
		"node_modules",
		"out",
		"build"
	]
}
```

And My servers `rootDir` is the default.

I would like my controller to import my service like this:
```typescript
import { service } from "services/service" // <-- like this
import { service } from "../services/service" // <-- not like this
...
```
This is of course a simple example, but in a bigger project I have many nested folders to my imports look like this: `../../../../path/to/class` which is hard to maintain.

My project compiles but in runtime I am getting the following error:
```
[2018-05-08T16:09:01.483] [ERROR] [TSED] - { Error: Cannot find module 'models/model'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/path/to/proj/controllers/ctrl.ts:25:19)
    at Module._compile (module.js:652:30)
    at Module.m._compile (/path/to/proj/node_modules/ts-node/src/index.ts:403:23)
    at Module._extensions..js (module.js:663:10)
    at Object.require.extensions.(anonymous function) [as .ts] (/path/to/proj/node_modules/ts-node/src/index.ts:406:12)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Promise.resolve.then (/path/to/proj/node_modules/@tsed/src/common/server/components/ServerLoader.ts:380:44)
    at <anonymous> code: 'MODULE_NOT_FOUND' }
```

Am I doing something wrong? Is it possible?
Thanks!

**Comment by Romakita** [comment]
Hello @TomerAmirV,

I understand your problem, and I have the same problem one project. Node.js doesn't provide a simple way to simplify your require path and it's normal.

For example:
```
import { service } from "services/service";
// is compiled to
const  {service } = require('services/service') // almost something like that
```
This syntax will always look on the node_modules directory and the global modules. So this syntax can't be used to get your file from the project root directory.

In fact, what is the project root directory ? How node.js can get this path ? maybe from the package.json ? Currently, we haven't this information.
The only information that we have, is the `process.cwd()` and it depend on the command launched to start your Node.js app.

So a syntax like that could be used, but is unsafe because it depend on the run context:
```
import { service } from "/services/service";
```

So the only way to simplify your require paht in your code is to create a npm module and use `npm link`. If you want manage your code with node package your can look on `lerna` or build your own solution with `npm link`.

I hope my explanation are clear and understandable  ;)

See you,
Romain

**Comment by TomerAmirV** [comment]
Yes, Thanks a lot!

it's a bit disappointing that there is no simple way to do it. I know `webpack` has a solution for web apps, but for now I'll make due with relative paths.

Thanks!

**Comment by teusemanuel** [comment]
Hi I found a solution using this lib. [tscpaths](https://github.com/joonhocho/tscpaths)

**Comment by TomerAmirV** [comment]
I finally found a solution that works for me using a package called `module-alias`:
https://dev.to/larswaechter/path-aliases-with-typescript-in-nodejs-4353

Highly recommended!
